source:
  type: "cldi"
  endpoint: "127.0.0.1"
  rpc_port: 50004
  executor_port: 50002
sink:
  type: "doris"
  endpoint: "http://127.0.0.1:8030"
  database: "citacloud1"
  user: "root"
  password: ""
#sink:
#  type: "csv"
#  path: "./output/"
range:
  start: 700
  end: 100000
  duration: 1
